openapi: 3.0.0
info:
  title: PFP Admin Management API
  version: 1.0.0
  description: API for Super Admins to manage projects and users in the multi-tenancy system.

servers:
  - url: /api
    description: Main API server

security:
  - bearerAuth: []

paths:
  /admin/projects:
    get:
      summary: List all projects
      tags: [Projects]
      responses:
        '200':
          description: List of projects
    post:
      summary: Create a new project
      tags: [Projects]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name: { type: string }
                slug: { type: string }
                settings: { type: object }
      responses:
        '201':
          description: Project created

  /admin/projects/{id}:
    put:
      summary: Update project
      tags: [Projects]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                status: { type: string, enum: [active, suspended] }
                settings: { type: object }
      responses:
        '200':
          description: Project updated

  /admin/users:
    get:
      summary: List all users
      tags: [Users]
      responses:
        '200':
          description: List of users with project names
    post:
      summary: Create a new user (Admin/Agent)
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, role]
              properties:
                email: { type: string }
                password: { type: string }
                name: { type: string }
                role: { type: string, enum: [super_admin, admin, agent] }
                projectId: { type: integer }
      responses:
        '201':
          description: User created

  /admin/users/{id}:
    put:
      summary: Update user assignment or role
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                role: { type: string, enum: [super_admin, admin, agent] }
                projectId: { type: integer }
                is_active: { type: boolean }
      responses:
        '200':
          description: User updated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
